spring.application.name=event-app-backend

spring.servlet.multipart.max-file-size=20MB
minio.url=http://localhost
minio.port=9000
minio.user=minioadmin
minio.password=minioadminpw
minio.bucket=files

spring.datasource.url=jdbc:mariadb://localhost:3306/spring
spring.datasource.username=db_user
spring.datasource.password=db_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

security.jwt.secret=averygoodsecretover9000