services:
  mariadb:
    image: mariadb:11.1
    container_name: bweng-backend
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: spring
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_password
    ports:
      - "3306:3306"
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: files
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data

volumes:
    minio:
